name: REGINSA Smoke Caso03 Cloud Placeholder

on:
  workflow_dispatch:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Use dedicated k6 caso03 workflow."
