name: REGINSA Smoke Caso02 Cloud Placeholder

on:
  workflow_dispatch:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Use dedicated k6 caso02 workflow."
