name: REGINSA SonarQube Placeholder

on:
  workflow_dispatch:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Workflow placeholder. Use dedicated Sonar workflow in repository."
