name: REGINSA Smoke Caso01 Cloud Placeholder

on:
  workflow_dispatch:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Use reginsa-k6-caso01-selfhosted workflow."
